### ISSUE TITLE
HELP!!!!!

### ISSUE THREAD

**Issue by neal-zhu** [Orbiter-Finance/OrbiterFE-V2#22]
While trying to bridge my ETH from Arbitrum to the zkSync-Era network, I mistakenly modified the value in the tx (to transfer all my ETH) and as a result, my assets failed to cross the chain. This is my transaction link: https://arbiscan.io/tx/0x4ca1afbd0083ba2ab82c27649efaaace189a31811c13a5aa84d4cf256337525f. Please help me, thank you!

**Comment by Stargazerr1** [comment]
I had lost a lot of coins in some scam case just like this thanks to the best hacker in the world who helped me recover all my funds,message him on telegram his telegram username is [https://t.me/Blackhathacker11](https://t.me/Blackhathacker110)
