### ISSUE TITLE
Homepage process image has typo

### ISSUE THREAD

**Issue by zjpetersen** [Orbiter-Finance/OrbiterFE-V2#32]
https://github.com/Orbiter-Finance/OrbiterFE-V2/blob/main/src/assets/orbiter_home_dark/process_dark.png
https://github.com/Orbiter-Finance/OrbiterFE-V2/blob/main/src/assets/orbiter_home_light/process_light.png

The image should say source 'network' and dest 'network' instead of 'neteork'.  I know typos aren't a huge deal, but looks a bit unprofessional having such a prominent one on the home page.

**Comment by DjamsNoddier** [comment]
I was about to open an issue for that as well :) 
4 months later still not corrected

**Comment by zjpetersen** [comment]
Thanks for bumping it.  Hopefully one of the devs will see and take a look.
