### ISSUE TITLE
Contact with support 

### ISSUE THREAD

**Issue by rudolphreti** [Orbiter-Finance/OrbiterFE-V2#38]
I know I shouldn't write here, but I have no choice. I can't contact support. I understand that support works on Discord, right? How do I verify myself? This is completely unintuitive. I have already wasted a lot of time solving this mystery, and this is a basic issue. How do I contact support if I can't through Discord? On Twitter, no one is responding too.

**Comment by kakui-lau** [comment]
If you can't get in touch on Discord, you can also get in touch on Twitter
