### ISSUE TITLE
Bug: Flop card animation covers button

### ISSUE THREAD

**Issue by 0xEljh** [Orbiter-Finance/OrbiterFE-V2#39]
![image](https://github.com/Orbiter-Finance/OrbiterFE-V2/assets/34589654/c0c774b0-7dfb-48c5-8933-b66e440d04bd)

Found a UI bug with the flop card component covering the button (as per the screenshot), this prevents the `continue` and `x` buttons from being clickable, except along the edge.

**Comment by bjeschke** [comment]
I have the same issue on Firefox. Please fix it here: 

.lottery-card-group-dialog .lottery-bg-3-animation {

**Comment by kakui-lau** [comment]
fix
